name: pokedex
description: Projecto de flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.2
  percent_indicator: ^4.0.0
  flutter_launcher_icons: ^0.11.0
  animated_text_kit: ^4.2.2
  simple_icons: ^7.10.0
  url_launcher: ^6.1.10
  zwidget: ^0.0.2
  badges: ^3.1.1

flutter_icons:
  android: true
  image_path: "assets/image/pika.png"
  
  ios: false
  remove_alpha_ios: true
  windows:
    generate: false
  web:
    generate: false
  macos:
    generate: false



dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/gif/
    - assets/image/


